[keyboard]
name = "VFLK"
product_name = "VFLK Keyboard"
vendor_id = 0xFEED
product_id = 0x9527
manufacturer = "kaumovich"
chip = "nrf52840"
usb_enable = true

[split]
connection = "ble"

[storage]
enabled = true



[layout]
rows = 6
cols = 13
layers = 4
keymap = [
    [
        ["Escape",    "F1",   "F2",     "F3",    "F4",    "F5",            "F6",     "F7",    "F8",      "F9",    "F10",           "F11",          "F12"       ],
        ["Grave",     "Kc1",  "Kc2",    "Kc3",   "Kc4",   "Kc5",           "Kc7",    "Kc8",   "Kc9",     "Kc0",   "Minus",        "Equal",        "Backspace"  ],
        ["Tab",       "Q",    "W",      "E",     "R",     "T",             "U",      "I",     "O",       "P",     "LeftBracket",   "RightBracket", "Backslash" ],
        ["CapsLock",  "A",    "S",      "D",     "F",     "G",             "H",      "J",     "K",       "L",     "Semicolon",     "Quote",        "Enter",    ],
        ["LShift",    "Z",    "X",      "C",     "V",     "B",             "N",      "M",     "Comma",   "Dot",   "RShift",        "Up",           "Slash",    ],
        ["LCtrl",     "LGui", "MO(1)",  "LAlt",  "Space", "Kc6",           "Y",      "Space", "MO(2)",   "RGui",    "Right",       "Down",         "Left",     ],    
    ],
    [
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],   
    ],
    [
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],   
    ],
    [
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],
        ["No", "No", "No", "No", "No", "No",     "No", "No", "No", "No", "No", "No", "No"  ],   
    ],
    
]


[split.central]
rows = 6
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "normal"
row_pins = ["P1_04", "P1_06", "P0_31", "P0_29", "P0_02", "P1_15"]
col_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11"]

[[split.peripheral]]
rows = 6
cols = 7
row_offset = 0
col_offset = 6

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_11", "P1_00", "P0_24", "P0_22", "P0_20", "P0_17"]
col_pins = ["P0_02", "P0_15", "P1_13", "P1_12", "P1_11", "P1_10", "P0_09"] 

[ble]
enabled = true
#battery_adc_pin = "vddh"
battery_adc_pin = "P0_28"
adc_divider_measured = 2000
adc_divider_total = 2806
charge_state.pin = "P0_03"
charge_state.low_active = false

[host]
vial_enabled = true
# unlock_keys = [[0, 0], [0, 1]]

# [aliases]
# my_cut = "WM(X, LCtrl)"
# my_copy = "WM(C, LCtrl)"
# my_paste = "WM(V, LCtrl)"
